name: Hugin Desktop Main Pipeline

env:
  GITHUB_REGISTRY: 'ghcr.io'
  GITHUB_OWNER: 'kryptokrona'

on:
  push:
    branches:
      - add-github-workflow # switch to main later
    paths-ignore:
      - '*.md'
      - '.run/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    name: "Build: ${{ matrix.config.name }}"
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false # set to true when ready
      matrix:
        config:
          - {
            name: "Windows Latest",
            os: windows-latest
          }
          - {
            name: "Ubuntu Latest",
            os: ubuntu-latest
          }
          - {
            name: "macOS Latest",
            os: macos-latest,
          }

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0

      - name: Build Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.HUGIN_DESKTOP_SECRET }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.comment.body }}
          regex: '```typescript([\s\S]*)```'
          flags: gm>

#      - name: "Upload ${{ matrix.config.name }} Artifact"
#        uses: actions/upload-artifact@v3
#        if: matrix.config.os == 'windows-latest'
#        with:
#          name: windows-latest-build
#          path: |
#            dist/Hugin Messenger Setup.exe
#
#      - name: "Upload ${{ matrix.config.name }} Artifact"
#        uses: actions/upload-artifact@v3
#        if: matrix.config.os == 'ubuntu-latest'
#        with:
#          name: ubuntu-latest-build
#          path: |
#            dist/Hugin Messenger Setup
#
#      - name: "Upload ${{ matrix.config.name }} Artifact"
#        uses: actions/upload-artifact@v3
#        if: matrix.config.os == 'macos-latest'
#        with:
#          name: macos-latest-build
#          path: |
#            dist/Hugin Messenger Setup.dmg
