name: Hugin Desktop Main Pipeline

env:
  GITHUB_REGISTRY: 'ghcr.io'
  GITHUB_OWNER: 'kryptokrona'
  GH_TOKEN: ${{ secrets.HUGIN_DESKTOP_SECRET }}

on:
  push:
    branches:
      - add-github-workflow # switch to main later
    paths-ignore:
      - '*.md'
      - '.run/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    name: "Build: ${{ matrix.config.name }} / ${{ matrix.config.platform }}"
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false # set to true when ready
      matrix:
        config:
          - {
            name: "Windows Latest",
            os: windows-latest,
            platform: x64
          }
          - {
            name: "Ubuntu Latest",
            os: ubuntu-latest,
            platform: x64
          }
          - {
            name: "macOS-11",
            os: macos-11,
            platform: x64
          }
          - {
            name: "macOS Latest",
            os: macos-latest,
            platform: arm64
          }

    env:
      PLATFORM: ${{ matrix.config.platform }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: npm install --quiet

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.os == 'windows-latest'
        run: npm run build

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.os == 'ubuntu-latest'
        run: npm run build:linux-$PLATFORM

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.os == 'macos-11'
        run: npm run build:mac-$PLATFORM

      - name: Build ${{ matrix.config.name }}
        if: matrix.config.os == 'macos-latest'
        run: npm run build:mac-$PLATFORM

      - name: "Upload ${{ matrix.config.name }} Artifact"
        uses: actions/upload-artifact@v3
        if: matrix.config.os == 'windows-latest'
        with:
          name: windows-latest-build
          path: |
            dist/HuginMessenger.exe

      - name: "Upload ${{ matrix.config.name }} Artifact"
        uses: actions/upload-artifact@v3
        if: matrix.config.os == 'ubuntu-latest'
        with:
          name: ubuntu-latest-build
          path: |
            dist/HuginMessenger

      - name: "Upload ${{ matrix.config.name }} Artifact"
        uses: actions/upload-artifact@v3
        if: matrix.config.os == 'macos-latest'
        with:
          name: macos-latest-build
          path: |
            dist/HuginMessenger.dmg
